### PR TITLE
[OBSDEF-9141] Make objectscale-manager upgradeable

### PR DESCRIPTION
**Pull request by tmarcu**
Signed-off-by: Tudor Marcu <Tudor.Marcu@emc.com>

## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [x] make test passed
- [x] make build passed
- [ ] helm install <chart> passed
- [x] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [x] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
```
objectscale-manager-alerts-84896c89df-k25d4                       4/4     Running          0          17m
objectscale-manager-bookkeeper-operator-78679c5d6b-ft5n9          2/2     Running          0          17m
objectscale-manager-fluxd-7dd95687f4-swsj7                        3/3     Running          0          17m
objectscale-manager-grafana-698f6c77c7-m8rlv                      5/5     Running          0          17m
objectscale-manager-influxdb-0                                    5/5     Running          0          16m
objectscale-manager-influxdb-1                                    5/5     Running          0          16m
objectscale-manager-influxdb-2                                    5/5     Running          0          16m
objectscale-manager-influxdb-operator-54d5b4d9b4-8t2hr            1/1     Running          0          17m
objectscale-manager-pravega-operator-5db5bcfc66-g5zrd             2/2     Running          0          17m
objectscale-manager-rsyslog-0                                     3/3     Running          0          16m
objectscale-manager-rsyslog-1                                     3/3     Running          0          16m
objectscale-manager-rsyslog-2                                     3/3     Running          0          16m
objectscale-manager-rsyslog-3                                     3/3     Running          0          16m
objectscale-manager-rsyslog-4                                     3/3     Running          0          16m
objectscale-manager-service-pod-f6465f696-tsm5g                   1/1     Running          0          17m
objectscale-manager-statefuldaemonset-operator-64fcf75987-9nhdv   1/1     Running          0          17m
objectscale-manager-telegraf-8769b8f6b-r648s                      3/3     Running          0          17m
objectscale-manager-throttler-5f94dd489d-g2gdh                    2/2     Running          0          17m
```

helm:
```
objectscale-manager     dellemc-global2-domain-c10      1               2021-06-15 00:22:01.932666751 +0000 UTC deployed        objectscale-manager-0.75.0  0.75.0     
```

### CODE REVIEW

**Review by eddiepavkovic — CHANGES_REQUESTED** [review]
Please run the jenkins job.  that'll at least verify no regressions with all of the objectscale-manager changes.

**Comment by tmarcu** [comment]
> Please run the jenkins job. that'll at least verify no regressions with all of the objectscale-manager changes.

https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/195/

Thanks I need to remember to run this right away

**Review by vgupta-mickey — APPROVED** [review]

**Review by eddiepavkovic — COMMENTED** [review]
looks great.  

Please post the link for the charts-custom-ci job thanks

**Review by eddiepavkovic — APPROVED** [review]
lgmt

**Pull request merged**
