### PR TITLE
VXFM-20482: Add securitycontext in deployment of decks and kahm

### PR DESCRIPTION
**Pull request by ankitagarwal1**
## Purpose
[OBSDEF-nnnn](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-nnnn)
_List the changes for this PR_

## PR checklist
- [ ] make test passed
- [ ] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
_Paste URL of charts-custom-ci job here_

_Paste the output of your helm install/vSphere7 deployment testing here_

### CODE REVIEW

**Review by eddiepavkovic — CHANGES_REQUESTED** [review]
i still don't understand the changes.  perhaps it should be wrapped in the context of Platform=Atlantic

**Comment by ankitagarwal1** [comment]
> i still don't understand the changes. perhaps it should be wrapped in the context of Platform=Atlantic

@eddiepavkovic Addressed the change and wrapped into context of Platform=Atlantic

**Comment by ankitagarwal1** [comment]
@eddiepavkovic As we have enabled RKE2 CIS 1.6 profiling on our cluster so for security reasons pods will run only with non root user. To run decks and kahm pod as non root user we have added securityContext changes to decks and kahm pods.
As we discussed your team is changing code to run as non root user . tbd around end of the month .So will wait by then

**Comment by vgupta-mickey** [comment]
Can you please explain what is needed here.? we are planning to built KAHM image itself as non-root so that you don't need add in the charts. Also there is anotehr PR which will ad fsGroup as well.

**Review by vgupta-mickey — CHANGES_REQUESTED** [review]
Need to understand the requirements. we are building a KAHM image with a non-root user and adding fsGroup as a part of separate PR.

**Comment by eddiepavkovic** [comment]
setting to a draft PR... we're actively making changes.  in 2.83.0 kahm is already running as non root.  
in 2.84.0 decks will get the similar change.

**Comment by eddiepavkovic** [comment]
closing.  addressed by PRs: #1025 and build 0.84.0 for kahm.   decks will be resolved with PR #1020

**Pull request closed without merging**
