### PR TITLE
[OBSDEF-7504] Create empty secret for objectscale-gateway and iam

### PR DESCRIPTION
**Pull request by SeemaTahaliyani**
## Purpose
[OBSDEF-7504] 
Created empty secret for objectscale-gateway and objectscale-iam

iam and gateway pods were failing on Vsphere because the secret is not available in time which is created by the operator. WIth the proposed change, we created empty secret in charts which then gets updated with cert data from the operator.

https://jira.cec.lab.emc.com/browse/OBSDEF-7504?focusedCommentId=6479910&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-6479910

## PR checklist
- [ ] make test passed
- [x] make build passed
- [ ] helm install <chart> passed
- [x] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [x] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
https://asd-ecs-jenkins.isus.emc.com/jenkins/job/charts-custom-ci/274/

_Paste the output of your helm install/vSphere7 deployment testing here_

### CODE REVIEW

**Review by lipak2345 — APPROVED** [review]

**Review by eddiepavkovic — CHANGES_REQUESTED** [review]
I'm concerned about these changes for upgrade.  The secrets may be wiped out.  Will they get regenerated or cause problems

**Comment by eddiepavkovic** [comment]
I think we want it do that the empty secret is created on first install.  If so we need to use the helm preinstall trick

**Comment by SeemaTahaliyani** [comment]
> I'm concerned about these changes for upgrade. The secrets may be wiped out. Will they get regenerated or cause problems

@eddiepavkovic secrets if wiped out, are recreated if operator pod restarts. Will operator pod restart during upgrade?

**Comment by SeemaTahaliyani** [comment]
> I think we want it do that the empty secret is created on first install. If so we need to use the helm preinstall trick

Sure this can be done. @voa808 can you please add annotations as in https://github.com/EMCECS/charts/blob/master/objectscale-federation/templates/shared_secret.yaml after discussing with Vinod Gupta and Eddie.

@vgupta-mickey Just curious what happens to the secrets during upgrade that are created by the operator?

**Comment by voa808** [comment]
> > I think we want it do that the empty secret is created on first install. If so we need to use the helm preinstall trick
> 
> Sure this can be done. @voa808 can you please add annotations as in https://github.com/EMCECS/charts/blob/master/objectscale-federation/templates/shared_secret.yaml after discussing with Vinod Gupta and Eddie.
> 
> @vgupta-mickey Just curious what happens to the secrets during upgrade that are created by the operator?

Annotation updated. charts ci job is in progress https://asd-ecs-jenkins.isus.emc.com/jenkins/job/charts-custom-ci/279/consoleFull

**Comment by voa808** [comment]
Retriggered ci job after the stonecold was fixed. https://asd-ecs-jenkins.isus.emc.com/jenkins/job/charts-custom-ci/281/
@eddiepavkovic @vgupta-mickey The latest charts ci passed. Could you please help to review the PR. Thanks.

**Review by eddiepavkovic — APPROVED** [review]
excellent,  please post the job that passed.

**Comment by eddiepavkovic** [comment]
I approved.

**Pull request merged**
