### PR TITLE
[OBSDEF-5312] Add support for objmt

### PR DESCRIPTION
**Pull request by shangxl1982**
## Purpose
https://jira.cec.lab.emc.com/browse/OBSDEF-5312
Add support for switching between new metering/old metering svc.

## PR checklist
- [x] make test passed
- [ ] make build passed
- [x] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

[root@linux:~/git/ecscharts/charts(feature-OBSDEF-5224-add-objmt-svc-support)]$ helm install ecs-cluster ecs-cluster --set s3.service.type=LoadBalancer --set managementGateway.service.type=LoadBalancer --set diagnostic.service.type=LoadBalancer --set performanceProfile=Small --set replicas=1 --set storageServer.replicas=1 --set storageServer.persistence.size=64Gi --set global.registry=asdrepo.isus.emc.com:8099 --set global.monitoring.enabled=false --set tag=0.65.0 --set objectsvc.image.tag=0.65.0 --set fabricProxy.image.tag=0.65.0 --set managementGateway.image.tag=0.65.0 --set provision.image.tag=0.65.0 --set deosEvents.image.tag=0.65.0 --set deos_hc.image.tag=0.65.0 --set features.enableCRR=false --set features.enableObjectStoreMetering=true --set features.objectType=objectSVC --set pullPolicy=IfNotPresent --set zookeeper.replicas=1 --set objectStoreMetering.image.tag=3.7.0.0-129723.a06be928b01
NAME: ecs-cluster
LAST DEPLOYED: Wed Jan 27 11:00:49 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
Thank you for installing ecs-cluster. This release provides a Dell EMC
Elastic Cloud Storage (ECS) Clusters for a highly scalable, private,
S3-compatible object storage.

Your release is named ecs-cluster.

To get started, simply read your access keys and endpoint(s):

  $ read -r ACCESS_KEY SECRET_KEY \
        <<<$(kubectl get secret ecs-cluster-initial-user -o jsonpath='{.data.accessKey}' | base64 -d; echo -n " "; kubectl get secret ecs-cluster-initial-user -o jsonpath='{.data.secretKey}' | base64 -d )
  $ read -r INTERNAL_ENDPOINT EXTERNAL_ENDPOINT \
        <<<$(kubectl get svc ecs-cluster-s3 \
        -o jsonpath='{.spec.clusterIP} {.status.loadBalancer.ingress[0].ip}')

NOTE: It may take a couple minutes for the Kubernetes cluster to assign a
      Load Balancer address. If it isn't set after a prolonged period, ensure
      that the Kubernetes cluster supports a "LoadBalancer" service type, or
      contact your Kubernetes provider support.
[root@linux:~/git/ecscharts/charts(feature-OBSDEF-5224-add-objmt-svc-support)]$ helm list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
ecs-cluster             default         1               2021-01-27 11:00:49.299123356 -0500 EST deployed        ecs-cluster-0.65.0              0.65.0
objectscale-manager     default         1               2021-01-22 03:54:31.578586994 -0500 EST deployed        objectscale-manager-0.65.0      0.65.0

[root@linux:~/git/ecscharts/charts(feature-OBSDEF-5224-add-objmt-svc-support)]$ kubectl get po
NAME                                                             READY   STATUS             RESTARTS   AGE
atlas-operator-7dc796946-tp9qb                                   1/1     Running            0          5d7h
ecs-cluster-atlas-0                                              1/1     Running            0          94s
ecs-cluster-cm-5b8576457b-vdrn7                                  2/3     Running            0          44s
ecs-cluster-control-767cfb4777-cztlz                             1/3     Running            0          44s
ecs-cluster-diag-5c54cf76d-49c8f                                 2/3     Running            0          44s
ecs-cluster-event-5f78b6dcd7-7q8lg                               2/3     Running            0          44s
ecs-cluster-geo-6454d65c4c-t5f9m                                 2/3     Running            0          44s
ecs-cluster-management-gateway-696ddb8b64-6vpfb                  2/2     Running            0          44s
ecs-cluster-objectsvc-67d99d9457-9lgdn                           2/3     Running            0          43s
ecs-cluster-objmt-6f97779df9-mnvkx                               2/3     Running            0          44s
ecs-cluster-resource-cbd95dd68-rn6zv                             2/3     Running            0          43s
ecs-cluster-rm-687d99c9bb-btp99                                  2/3     Running            0          43s
ecs-cluster-s3-5c85cc75f8-npwsc                                  2/3     Running            0          43s
ecs-cluster-sr-84584d4456-59m5m                                  2/3     Running            0          43s
ecs-cluster-ss-0                                                 2/2     Running            0          63s
ecs-cluster-ssm-5588dd985d-h4txs                                 2/3     Running            0          42s
ecs-cluster-zookeeper-0                                          1/1     Running            0          61s
objectscale-manager-fluxd-664cb59654-4hxvl                       1/1     Running            0          5d7h
objectscale-manager-grafana-766c9556f8-zzt6j                     2/2     Running            0          5d7h
objectscale-manager-influxdb-0                                   3/3     Running            0          5d7h
objectscale-manager-influxdb-operator-76dcbbfd6f-p8r5r           1/1     Running            0          5d7h
objectscale-manager-prometheus-alerts-684bdd69b6-74vhc           2/2     Running            0          5d7h
objectscale-manager-rsyslog-0                                    3/3     Running            0          5d7h
objectscale-manager-service-pod-7c65689d7-9gzvh                  1/1     Running            0          5d7h
objectscale-manager-statefuldaemonset-operator-9b6c878b5-mwc65   1/1     Running            0          5d7h
objectscale-manager-telegraf-774dc8cfd4-vpzpj                    1/1     Running            0          5d7h
objectscale-manager-throttler-7cb9499768-862sx                   1/1     Running            0          5d7h
objectscale-operator-58cfb759c5-5w558                            1/1     Running            0          26h
objectscale-syslog-0                                             0/1     CrashLoopBackOff   2507       5d5h
zookeeper-operator-54cbdb454-gcpj2                               1/1     Running            0          33h

### CODE REVIEW

**Review by eddiepavkovic — CHANGES_REQUESTED** [review]
helm unittest broke,  please fix before merging to master.

**Comment by shangxl1982** [comment]
> helm unittest broke, please fix before merging to master.

ut fixed.

**Comment by shangxl1982** [comment]
> helm unittest broke, please fix before merging to master.

ut fixed

**Review by fedor-chemashkin — APPROVED** [review]

**Review by shangxl1982 — COMMENTED** [review]
fixed ut.

**Review by shangxl1982 — COMMENTED** [review]
ut fixed

**Review by yiye-dev — APPROVED** [review]

**Review by eddiepavkovic — APPROVED** [review]
ok looks good.

**Pull request merged**
