### PR TITLE
[OBSDEF-8292] There is no way by which TMM rejection by Operator can be bypassed. Bypass TMM checks

### PR DESCRIPTION
**Pull request by AndreyAdnreyev**
## Purpose
[OBSDEF-8292](https://jira.cec.lab.emc.com/browse/OBSDEF-8292)
Add a configmap with bypass values that used in operator.

## PR checklist
- [ ] make test passed
- [x ] make build passed
- [ ] helm install <chart> passed
- [x ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [x ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing

- https://asd-ecs-jenkins.isus.emc.com/view/ECS-Flex/job/charts-custom-ci/321/
- manual tests

### CODE REVIEW

**Review by eddiepavkovic — CHANGES_REQUESTED** [review]
does this need to be in beta3?  the bug is targetted for beta3...

**Comment by AndreyAdnreyev** [comment]
yes, I'm doing another PR for beta3

**Comment by eddiepavkovic** [comment]
This is a P1 was it approved by in the objectscale-echo-shiproom slack channel.

**Comment by BassinD** [comment]
We already have CM to bypass service procedures in the SP operator https://github.com/EMCECS/charts/blob/master/objectscale-manager/templates/objectscale-manager-service-procedures-configmap.yaml. Maybe you can add ` objectscale-manager-bypass-config.yaml:` in it instead of creating the new one?

**Comment by AndreyAdnreyev** [comment]
In this case both code bases will be tightly coupled. Any change in objectscale-manager-service-procedures-configmap.yaml may create a side effect on one of operators. Also, it is additional complexity to support this coupling.

**Comment by BassinD** [comment]
> In this case both code bases will be tightly coupled. Any change in objectscale-manager-service-procedures-configmap.yaml may create a side effect on one of operators. Also, it is additional complexity to support this coupling.

I agree with your solution too. Just wanted to reduce the number of meta-objects and to have a single place where by-pass can be configured (like logger config). Side effect on operators is not critical, because it's just an update of configuration which is not high-load.

**Review by BassinD — APPROVED** [review]

**Pull request merged**
