### PR TITLE
[OBSDEF-7181] change dcm to static name similar to other objectscale services

### PR DESCRIPTION
**Pull request by sumithreddy**
## Purpose
[OBSDEF-7181](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7181)
1) https://jira.cec.lab.emc.com/browse/OBSDEF-8957 First step towards objectscale gateway integration
2) gateway relies on static service names

## PR checklist
- [x] make test passed
- [x] make build passed
- [x] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

<pre><font color="#D3D7CF"><b>objectscale-dcm                  LoadBalancer   10.96.20.11     172.17.100.1   9026:31407/TCP               4m34s</b></font>
<font color="#D3D7CF"><b>objectscale-dcm-atlas-client     ClusterIP      10.96.162.145   &lt;none&gt;         8080/TCP,8090/TCP            4m13s</b></font>
<font color="#D3D7CF"><b>objectscale-dcm-atlas-headless   ClusterIP      None            &lt;none&gt;         8080/TCP,8090/TCP,9207/TCP   4m13s</b></font>
</pre>

<pre><font color="#D3D7CF"><b>objectscale-dcm-atlas-0                                   1/1     Running                 0          102s</b></font>
<font color="#D3D7CF"><b>objectscale-dcm-c54c9b9c7-svrpx                           1/1     Running                 0          2m4s</b></font>
</pre>

### CODE REVIEW

**Review by abercj2 — APPROVED** [review]

**Comment by eddiepavkovic** [comment]
it failed `make test`

did we test vsphere & perhaps openshift with these changes?   did we update dependent charts?

Could we please fill out the checklist above?

**Comment by sumithreddy** [comment]
> it failed `make test`
> 
> did we test vsphere & perhaps openshift with these changes? did we update dependent charts?
> 
> Could we please fill out the checklist above?

I am working on the PR checklist and fill them once done.

**Comment by sumithreddy** [comment]
> it failed `make test`
> 
> did we test vsphere & perhaps openshift with these changes? did we update dependent charts?
> 
> Could we please fill out the checklist above?

Its because its missing the chart package in the objectscale-manager charts

**Comment by sumithreddy** [comment]
@eddiepavkovic I finished the checklist. I installed it on minikube though. 
This change of chart name will break upgrade I guess ?

**Review by skripg — APPROVED** [review]

**Review by eddiepavkovic — APPROVED** [review]
lgmt

**Pull request merged**
