### PR TITLE
[OBSDEF-9772] add MY_OBJECTSCALE_NAMESPACE to env vars for iam client

### PR DESCRIPTION
**Pull request by abercj2**
## Purpose
[OBSDEF-9772](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-9772)
add MY_OBJECTSCALE_NAMESPACE to DCM env vars for iam client

## PR checklist
- [ ] make test passed
- [x] make build passed
- [x] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed
- [ ] Passed - https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/

## Testing
https://asd-ecs-jenkins.isus.emc.com/jenkins/view/ECS-Flex/job/charts-custom-ci/243/

deploy objectscale manager on minikube
```
 ENABLE_PRAVEGA=true
+ ENABLE_GATEWAY=true
+ ENABLE_DCM=true
+ ENABLE_MONITORING=false
+ REPLICAS=1
+ REGISTRY=asdrepo.isus.emc.com:8099
+ STORAGE_CLASS=standard
+ helm install ecs-manager charts/objectscale-manager --set global.storageClass=standard --set global.registry=asdrepo.isus.emc.com:8099 --set global.monitoring.enabled=false --set pullPolicy=IfNotPresent --set objectscale-iam.atlas.replicaCount=1 --set objectscale-iam.replicaCount=1 --set federation.fedsvc.replicaCount=1 --set federation.atlas.replicaCount=1 --set objectscale-dcm.atlas.replicaCount=1 --set objectscale-gateway.enabled=true --set dcm.enabled=true --set pravega.enabled=true --set bookkeeper.enabled=true
NAME: ecs-manager
LAST DEPLOYED: Fri Jul  2 17:40:22 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing objectscale-manager. This release is capable of
deploying and upgrading Dell EMC Elastic Cloud Storage (ECS) Clusters for a
highly scalable, private, S3-compatible object storage.

Your release is named ecs-manager.

To get started, install your first ECS cluster, you can use the Helm chart:

  $ helm install <repository name>/ecs-cluster

For more information on the installation and configuration options, see the
README at https://github.com/EMCECS/charts/tree/master/ecs-cluster and the
`values.yaml` file at
https://github.com/EMCECS/charts/blob/master/ecs-cluster/values.yaml
```
verify new environment var
```
kubectl describe pod objectscale-dcm-8dc6b7fbd-nnl8h
...
    Environment:
      SPRING_PROFILES_ACTIVE:    atlas,flex,dns
      ATLAS_SERVICE_HOSTNAME:    objectscale-dcm-atlas-client
      MY_POD_NAME:               objectscale-dcm-8dc6b7fbd-nnl8h (v1:metadata.name)
      MY_OBJECTSCALE_NAMESPACE:  default (v1:metadata.namespace)
      MY_POD_NAMESPACE:          default (v1:metadata.namespace)
      MY_POD_IP:                  (v1:status.podIP)
...
```

### CODE REVIEW

**Review by skripg — APPROVED** [review]

**Review by eddiepavkovic — CHANGES_REQUESTED** [review]
No changes needed.  There's already MY_POD_NAMESPACE set to the same value.  Use that or rename it.

**Comment by skripg** [comment]
@eddiepavkovic Thank you for pointing this. We had one and thought it should be enough but Bala asked to duplicate MY_POD_NAMESPACE to MY_OBJECTSCALE_NAMESPACE because they internally use MY_OBJECTSCALE_NAMESPACE and it is already duplicated in iamsvc https://github.com/EMCECS/charts/blob/13ee03a01f2b5d0a51972ca1dcc5cce276f3c140/objectscale-iam/templates/deployment.yaml#L410. We do not know why MY_POD_NAMESPACE was not used, probably @yuanyuanzhang87  or @SeemaTahaliyani 
 can give more details , regarding removing existing MY_POD_NAMESPACE  and keeping only MY_OBJECTSCALE_NAMESPACE I am not sure what regression it can cause, if you are confident it will not bring any regression we can remove MY_POD_NAMESPACE . https://jira.cec.lab.emc.com/browse/OBSDEF-9773?focusedCommentId=6235491&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6235491

**Comment by abercj2** [comment]
Within an objectstore, I believe MY_POD_NAMESPACE and MY_OBJECTSCALE_NAMESPACE can be different if the objectstore is in a different namespace. https://jira.cec.lab.emc.com/browse/OBSDEF-9231 That is why MY_OBJECTSCALE_NAMESPACE is there to get from within an objectstore up to the correct iamsvc. However, at the objectscale level, there is no difference. It's unclear why either is needed, but to keep the logic consistent, we can rename MY_POD_NAMESPACE since I don't see it used anywhere in the code

**Comment by lipak2345** [comment]
@abercj2 is correct, we conceptually discriminate between the namespace the pod is running on and where the common services are available.

**Review by eddiepavkovic — APPROVED** [review]
ok looks good.

please run the custom ci charts job to ensure no regressions.

**Pull request merged**
