### PR TITLE
[OBSDEF-7726] fedsvc log injection to rsyslog

### PR DESCRIPTION
**Pull request by voa808**
Update Federation template to inject logs from stdout to rsyslog using fluentd

Note:
There was an issue from Vmware which prevented us from collecting stdout logs on vsphere which is fixed but yet to be tested. There is a Jira tracking the same https://jira.cec.lab.emc.com/browse/OBSDEF-6252, fix version is Echo Beta3.

Testing: 
- https://asd-ecs-jenkins.isus.emc.com/jenkins/job/charts-custom-ci/129/console - In progress
- Manual Tests:  https://jira.cec.lab.emc.com/browse/OBSDEF-7726?focusedCommentId=5687100&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5687100
- make build: Passed
- make test: 2 charts lint failed. Tested on master same failed there as well. Details can be found here.
https://jira.cec.lab.emc.com/browse/OBSDEF-7726?focusedCommentId=5698593&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5698593

## Purpose
[OBSDEF-7726](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7726)
_List the changes for this PR_
Updated the template for federation service.

## PR checklist
- [x] make test passed
- [x] make build passed
- [x] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_
Installed objectscale manager using script: (details can be found here, https://jira.cec.lab.emc.com/browse/OBSDEF-7726?focusedCommentId=5687100&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5687100)
[root@linux:~/EMCECS/charts(bugfix-OBSDEF-7726-fedsvc-logging)]$ ./install-osman-barb.sh
```
+ ENABLE_PRAVEGA=false
+ ENABLE_GATEWAY=false
+ ENABLE_DCM=false
+ ENABLE_MONITORING=true
+ FLEX_TAG=0.71.2
+ OPERATOR_TAG=0.71.2
+ IAMSVC_TAG=0.71.2
+ FEDSVC_TAG=0.71.2
+ DCM_TAG=0.71.2
+ GATEWAY_TAG=0.71.2
+ REPLICAS=1
+ REGISTRY=asdrepo.isus.emc.com:8099
+ STORAGE_CLASS=standard
+ kubectl apply -f /root/metallb.yaml
namespace/metallb-system unchanged
podsecuritypolicy.policy/speaker unchanged
serviceaccount/controller unchanged
serviceaccount/speaker unchanged
clusterrole.rbac.authorization.k8s.io/metallb-system:controller unchanged
clusterrole.rbac.authorization.k8s.io/metallb-system:speaker unchanged
role.rbac.authorization.k8s.io/config-watcher unchanged
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:controller unchanged
clusterrolebinding.rbac.authorization.k8s.io/metallb-system:speaker unchanged
rolebinding.rbac.authorization.k8s.io/config-watcher unchanged
daemonset.apps/speaker unchanged
deployment.apps/controller unchanged
+ kubectl apply -f /root/metallb-config.yaml
configmap/config unchanged
++ kubectl create clusterrolebinding kubesystem-default-v-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "kubesystem-default-v-cluster-admin" already exists
+ echo

+ helm install ecs-manager objectscale-manager --set global.storageClass=standard --set global.registry=asdrepo.isus.emc.com:8099 --set global.monitoring.enabled=true --set pullPolicy=IfNotPresent --set image.tag=0.71.2 --set objectscale-iam.atlas.replicaCount=1 --set objectscale-iam.replicaCount=1 --set objectscale-iam.image.tag=0.71.2 --set federation.fedsvc.image.tag=0.71.2 --set federation.fedsvc.replicaCount=1 --set objectscale-gateway.objectscaleGateway.image.tag=0.71.2 --set objectscale-gateway.enabled=false --set dcm.enabled=false --set dcm.image.tag=0.71.2 --set pravega.enabled=false --set bookkeeper.enabled=false --set global.fluent_bit_enabled=true
NAME: ecs-manager
LAST DEPLOYED: Thu Apr 29 21:40:34 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing objectscale-manager. This release is capable of
deploying and upgrading Dell EMC Elastic Cloud Storage (ECS) Clusters for a
highly scalable, private, S3-compatible object storage.

Your release is named ecs-manager.

To get started, install your first ECS cluster, you can use the Helm chart:

  $ helm install <repository name>/ecs-cluster

For more information on the installation and configuration options, see the
README at https://github.com/EMCECS/charts/tree/master/ecs-cluster and the
`values.yaml` file at
https://github.com/EMCECS/charts/blob/master/ecs-cluster/values.yaml

```

### CODE REVIEW

**Review by pmmusial — APPROVED** [review]

**Review by victor-polyansky — APPROVED** [review]

**Comment by voa808** [comment]
As per discussion with @victor-polyansky today, the proposed solution in this PR (adding release label) covers only Openshift logging. We need to add labels to inject rsyslog-client, so stdout logs would be collected on vsphere 7u3, will raise a separate PR for the same.
Note: fluentbit is not supported on vsphere and Rsyslog client solution will work only on vsphere. Hence, we need rsyslog-client inside the pod to collect logs on vsphere.

**Review by eddiepavkovic — APPROVED** [review]
ok

**Comment by eddiepavkovic** [comment]
@voa808 is this still required?  or is it covered by #852

**Comment by voa808** [comment]
> @voa808 is this still required? or is it covered by #852

No, this is not required. It is covered by https://github.com/EMCECS/charts/pull/844

**Pull request closed without merging**
