### PR TITLE
[OBSDEF-7954] add sp operator labels to stateless components

### PR DESCRIPTION
**Pull request by BassinD**
## Purpose
[OBSDEF-7954](https://jira.cec.lab.emc.com:8443/browse/OBSDEF-7954)

| Components|      sp-integrated label|  vsphere-emm-integrated annotation |
|:----------:|:-------------:|:------:|
| DECKS | true | true |
| DECKS support store| true | true |
| KAHM | true | true |
| SupportAssist | true | true |
| ObjectScale IAM (w/o Atlas)| true | true |
| ObjectScale FedSVC (w/o Atlas)| true | true |
| ObjectScale DCM (w/o Atlas)| true | true |
| Install controller | true | true |
| influxdb-operator | true | true |
| objectscale-gateway | true | true |
| GraphQL | true | true |
| Operator (+SP operator) | true | true |
| objectscale-portal (UI) | true | true |
| pravega-operator | true | true |
| zookeeper-operator | true | true |
| service-pod | true | true |

## PR checklist
- [x] make test passed
- [x] make build passed
- [ ] helm install <chart> passed
- [ ] vSphere7 make package deployments passed
- [ ] helm upgrade <chart> passed
- [ ] helm test <release_name> passed

## Testing
_Paste the output of your helm install/vSphere7 deployment testing here_

### CODE REVIEW

**Review by antonbassin — APPROVED** [review]

**Comment by BassinD** [comment]
Local run of `make test` passed https://gist.github.com/BassinD/86fa5626ef495f22a37046a591eb6459

**Comment by eddiepavkovic** [comment]
Please add annotations for decks-support-store.  it will be converted to a deployment.

**Review by eddiepavkovic — DISMISSED** [review]
please add annotations for decks-support-store

**Comment by BassinD** [comment]
Added changes to the decks-support-store. `make-test` passed

**Pull request merged**
